name: Deploy to DockerHub and GHCR

on:
  push:
    branches: [master]

env:
  GH_PACKAGE: ghcr.io/${{ github.repository }}:latest
  DOCKER_PACKAGE: ${{ secrets.DOCKER_USERNAME }}/ctf-ub:latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push images and manifests
        run: ./docker-build.sh ${{ env.DOCKER_PACKAGE }} ${{ env.GH_PACKAGE }}
